# Generated by Django 4.2.30 on 2026-07-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('vacuum_status', models.CharField(default='Ready', max_length=50)),
                ('index_status', models.CharField(default='-', max_length=50)),
                ('rebuild_status', models.CharField(default='-', max_length=50)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('table_size', models.CharField(blank=True, max_length=50, null=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['table_name'],
            },
        ),
    ]
