# Generated by Django 4.2.30 on 2026-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('router', models.GenericIPAddressField(blank=True, null=True)),
                ('dns', models.GenericIPAddressField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
