# Generated by Django 4.2.30 on 2026-07-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='open_ports',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
