# Generated by Django 4.2.30 on 2026-07-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_scan_latency_ms_scan_mac_address_scan_open_ports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='device',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scan',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='os',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['ip', 'scanned_at'], name='scan_scan_ip_376dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['os', 'brand'], name='scan_scan_os_fa401a_idx'),
        ),
    ]
