# Generated by Django 4.2.30 on 2026-07-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='device',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scan',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='os',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['device'], name='scan_scan_device_32b034_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['mac_address'], name='scan_scan_mac_add_5e7b3f_idx'),
        ),
    ]
