# Generated by Django 4.2.30 on 2026-07-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_clean_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='isp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='isp_org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='server_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['public_ip'], name='scan_scan_public__0e17ed_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['isp_name'], name='scan_scan_isp_nam_bb50fc_idx'),
        ),
    ]
