# Generated by Django 6.0.7 on 2026-07-23 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_scan_isp_name_scan_isp_org_scan_public_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanMacHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['ip', 'last_seen'], name='scan_scanma_ip_e3eaed_idx'), models.Index(fields=['mac_address'], name='scan_scanma_mac_add_1161bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_entries', to='scan.scan')),
            ],
            options={
                'ordering': ['port'],
                'indexes': [models.Index(fields=['port'], name='scan_scanpo_port_c61167_idx')],
                'unique_together': {('scan', 'port')},
            },
        ),
    ]
