# Generated by Django 6.0.7 on 2026-07-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_scanmachistory_scanport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='scan',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanmachistory',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
