# Generated by Django 6.0.7 on 2026-07-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0007_alter_scan_ip_alter_scan_public_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuiVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=6, unique=True)),
                ('vendor', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['prefix'],
                'indexes': [models.Index(fields=['prefix'], name='scan_ouiven_prefix_5feef7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(unique=True)),
                ('service', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['port'],
                'indexes': [models.Index(fields=['port'], name='scan_portse_port_2859f7_idx')],
            },
        ),
    ]
