# Generated by Django 6.0.7 on 2026-07-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0008_ouivendor_portservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='IspInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('as_number', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['ip'], name='scan_ispinf_ip_1b7be7_idx'), models.Index(fields=['country'], name='scan_ispinf_country_84e6af_idx'), models.Index(fields=['city'], name='scan_ispinf_city_746ff1_idx')],
            },
        ),
    ]
