# Generated by Django 6.0.7 on 2026-07-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0009_ispinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('hops', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destination', 'created_at'], name='scan_connec_destina_4aa6f3_idx')],
            },
        ),
    ]
