# Generated by Django 6.0.7 on 2026-07-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0010_connectiontrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontrace',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectiontrace',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='connectiontrace',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='connectiontrace',
            index=models.Index(fields=['trace_id'], name='scan_connec_trace_i_5286a6_idx'),
        ),
        migrations.AddIndex(
            model_name='connectiontrace',
            index=models.Index(fields=['status'], name='scan_connec_status_b37db5_idx'),
        ),
    ]
