from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from django.core.cache import cache
from apps.scan.models import Scan, ScanPort, ScanMacHistory, OuiVendor, PortService
from apps.dashboard.models import DbMaintenance

User = get_user_model()


class Command(BaseCommand):
    help = 'Seed initial data (skips if data already exists)'

    def handle(self, *args, **kwargs):
        seeded = False

        if not User.objects.exists():
            User.objects.create_superuser('admin', 'admin@example.com', 'admin123')
            self.stdout.write(self.style.SUCCESS('Created superuser: admin / admin123'))
            seeded = True
        else:
            self.stdout.write(self.style.NOTICE('Superuser already exists, skipping.'))

        if not Scan.objects.exists():
            Scan.objects.create(
                ip='192.168.1.1',
                device='Gateway Router',
                os='Linux',
                brand='TP-Link',
                gateway='192.168.1.1',
                router='192.168.1.1',
                dns='8.8.8.8',
                mac_address='AA:BB:CC:DD:EE:FF',
                latency_ms=1.2,
                open_ports=['80', '443'],
                services={'80': 'HTTP', '443': 'HTTPS'},
                public_ip='203.0.113.10',
                isp_name='Example ISP',
                isp_org='Example ISP Org',
                server_info='nginx/1.18.0',
            )
            Scan.objects.create(
                ip='192.168.1.100',
                device='Workstation-PC',
                os='Windows 11',
                brand='Dell',
                gateway='192.168.1.1',
                router='192.168.1.1',
                dns='8.8.8.8',
                mac_address='11:22:33:44:55:66',
                latency_ms=3.5,
                open_ports=['135', '139', '445'],
                services={'135': 'MSRPC', '139': 'NetBIOS', '445': 'SMB'},
                public_ip='203.0.113.10',
                isp_name='Example ISP',
                isp_org='Example ISP Org',
                server_info=None,
            )
            Scan.objects.create(
                ip='192.168.1.50',
                device='iPhone-14',
                os='iOS 17.4',
                brand='Apple',
                gateway='192.168.1.1',
                router='192.168.1.1',
                dns='8.8.8.8',
                mac_address='A1:B2:C3:D4:E5:F6',
                latency_ms=5.1,
                open_ports=[],
                services=None,
                public_ip='203.0.113.10',
                isp_name='Example ISP',
                isp_org='Example ISP Org',
                server_info=None,
            )

            scan_gateway = Scan.objects.get(ip='192.168.1.1')
            ScanPort.objects.bulk_create([
                ScanPort(scan=scan_gateway, port=80, service='HTTP'),
                ScanPort(scan=scan_gateway, port=443, service='HTTPS'),
            ])

            scan_pc = Scan.objects.get(ip='192.168.1.100')
            ScanPort.objects.bulk_create([
                ScanPort(scan=scan_pc, port=135, service='MSRPC'),
                ScanPort(scan=scan_pc, port=139, service='NetBIOS'),
                ScanPort(scan=scan_pc, port=445, service='SMB'),
            ])

            ScanMacHistory.objects.bulk_create([
                ScanMacHistory(ip='192.168.1.1', mac_address='AA:BB:CC:DD:EE:FF'),
                ScanMacHistory(ip='192.168.1.100', mac_address='11:22:33:44:55:66'),
                ScanMacHistory(ip='192.168.1.50', mac_address='A1:B2:C3:D4:E5:F6'),
            ])
            self.stdout.write(self.style.SUCCESS('Seeded 3 sample scan records with ports and MAC history.'))
            seeded = True
        else:
            self.stdout.write(self.style.NOTICE('Scan records already exist, skipping.'))

        if not DbMaintenance.objects.exists():
            DbMaintenance.objects.bulk_create([
                DbMaintenance(table_name='scan', vacuum_status='Ready', index_status='-', rebuild_status='-'),
                DbMaintenance(table_name='auth_user', vacuum_status='Ready', index_status='-', rebuild_status='-'),
                DbMaintenance(table_name='dashboard_dbmaintenance', vacuum_status='Ready', index_status='-', rebuild_status='-'),
            ])
            self.stdout.write(self.style.SUCCESS('Seeded DbMaintenance records.'))
            seeded = True
        else:
            self.stdout.write(self.style.NOTICE('DbMaintenance records already exist, skipping.'))

        if not OuiVendor.objects.exists():
            OuiVendor.objects.bulk_create([
                OuiVendor(prefix='001122', vendor='Cisco'),
                OuiVendor(prefix='00199D', vendor='Cisco'),
                OuiVendor(prefix='0021A1', vendor='Cisco'),
                OuiVendor(prefix='001A79', vendor='Cisco'),
                OuiVendor(prefix='001EBD', vendor='Cisco'),
                OuiVendor(prefix='002155', vendor='Cisco'),
                OuiVendor(prefix='00259C', vendor='Cisco'),
                OuiVendor(prefix='00265A', vendor='Dell'),
                OuiVendor(prefix='0026B9', vendor='Dell'),
                OuiVendor(prefix='001422', vendor='Dell'),
                OuiVendor(prefix='001CC4', vendor='Dell'),
                OuiVendor(prefix='00219B', vendor='Dell'),
                OuiVendor(prefix='002219', vendor='HP'),
                OuiVendor(prefix='00237D', vendor='HP'),
                OuiVendor(prefix='002655', vendor='HP'),
                OuiVendor(prefix='000E7F', vendor='HP'),
                OuiVendor(prefix='001F29', vendor='HP'),
                OuiVendor(prefix='00215A', vendor='HP'),
                OuiVendor(prefix='002312', vendor='Apple'),
                OuiVendor(prefix='002332', vendor='Apple'),
                OuiVendor(prefix='002361', vendor='Apple'),
                OuiVendor(prefix='0023DF', vendor='Apple'),
                OuiVendor(prefix='002436', vendor='Apple'),
                OuiVendor(prefix='00254B', vendor='Apple'),
                OuiVendor(prefix='0025BC', vendor='Apple'),
                OuiVendor(prefix='00264A', vendor='Apple'),
                OuiVendor(prefix='0026B0', vendor='Apple'),
                OuiVendor(prefix='0026BB', vendor='Apple'),
                OuiVendor(prefix='003065', vendor='Apple'),
                OuiVendor(prefix='0050E4', vendor='Apple'),
                OuiVendor(prefix='040CCE', vendor='Apple'),
                OuiVendor(prefix='041552', vendor='Apple'),
                OuiVendor(prefix='041E64', vendor='Apple'),
                OuiVendor(prefix='042665', vendor='Apple'),
                OuiVendor(prefix='045453', vendor='Apple'),
                OuiVendor(prefix='04DB56', vendor='Apple'),
                OuiVendor(prefix='080007', vendor='Apple'),
                OuiVendor(prefix='101C0C', vendor='Apple'),
                OuiVendor(prefix='183DA2', vendor='Apple'),
                OuiVendor(prefix='20C9D0', vendor='Apple'),
                OuiVendor(prefix='28CFDA', vendor='Apple'),
                OuiVendor(prefix='2CBE08', vendor='Apple'),
                OuiVendor(prefix='3010B3', vendor='Apple'),
                OuiVendor(prefix='3035AD', vendor='Apple'),
                OuiVendor(prefix='380F4A', vendor='Apple'),
                OuiVendor(prefix='3C0754', vendor='Apple'),
                OuiVendor(prefix='403005', vendor='Apple'),
                OuiVendor(prefix='406C8F', vendor='Apple'),
                OuiVendor(prefix='442A60', vendor='Apple'),
                OuiVendor(prefix='4860BC', vendor='Apple'),
                OuiVendor(prefix='48746E', vendor='Apple'),
                OuiVendor(prefix='542696', vendor='Apple'),
                OuiVendor(prefix='544E90', vendor='Apple'),
                OuiVendor(prefix='581CF8', vendor='Apple'),
                OuiVendor(prefix='587F57', vendor='Apple'),
                OuiVendor(prefix='58B035', vendor='Apple'),
                OuiVendor(prefix='5C8D4E', vendor='Apple'),
                OuiVendor(prefix='600308', vendor='Apple'),
                OuiVendor(prefix='60C547', vendor='Apple'),
                OuiVendor(prefix='64200C', vendor='Apple'),
                OuiVendor(prefix='685B35', vendor='Apple'),
                OuiVendor(prefix='6C4008', vendor='Apple'),
                OuiVendor(prefix='6C72E7', vendor='Apple'),
                OuiVendor(prefix='701124', vendor='Apple'),
                OuiVendor(prefix='7014A6', vendor='Apple'),
                OuiVendor(prefix='703E97', vendor='Apple'),
                OuiVendor(prefix='741BB2', vendor='Apple'),
                OuiVendor(prefix='784F43', vendor='Apple'),
                OuiVendor(prefix='786A89', vendor='Apple'),
                OuiVendor(prefix='7C11BE', vendor='Apple'),
                OuiVendor(prefix='7C6D62', vendor='Apple'),
                OuiVendor(prefix='80BE05', vendor='Apple'),
                OuiVendor(prefix='843835', vendor='Apple'),
                OuiVendor(prefix='8478AC', vendor='Apple'),
                OuiVendor(prefix='88532E', vendor='Apple'),
                OuiVendor(prefix='88AE07', vendor='Apple'),
                OuiVendor(prefix='88CB87', vendor='Apple'),
                OuiVendor(prefix='8C1AB4', vendor='Apple'),
                OuiVendor(prefix='8C5877', vendor='Apple'),
                OuiVendor(prefix='9027E4', vendor='Apple'),
                OuiVendor(prefix='907240', vendor='Apple'),
                OuiVendor(prefix='90840D', vendor='Apple'),
                OuiVendor(prefix='949426', vendor='Apple'),
                OuiVendor(prefix='9801A7', vendor='Apple'),
                OuiVendor(prefix='9C04EB', vendor='Apple'),
                OuiVendor(prefix='9C207B', vendor='Apple'),
                OuiVendor(prefix='9C2976', vendor='Apple'),
                OuiVendor(prefix='9C35EB', vendor='Apple'),
                OuiVendor(prefix='9CF48E', vendor='Apple'),
                OuiVendor(prefix='A0999B', vendor='Apple'),
                OuiVendor(prefix='A4B197', vendor='Apple'),
                OuiVendor(prefix='A4C361', vendor='Apple'),
                OuiVendor(prefix='A4D18C', vendor='Apple'),
                OuiVendor(prefix='A82066', vendor='Apple'),
                OuiVendor(prefix='A85B78', vendor='Apple'),
                OuiVendor(prefix='A89675', vendor='Apple'),
                OuiVendor(prefix='AC3A7A', vendor='Apple'),
                OuiVendor(prefix='ACBC32', vendor='Apple'),
                OuiVendor(prefix='B03495', vendor='Apple'),
                OuiVendor(prefix='B81799', vendor='Apple'),
                OuiVendor(prefix='B827EB', vendor='Apple'),
                OuiVendor(prefix='B8C75D', vendor='Apple'),
                OuiVendor(prefix='BC3BAF', vendor='Apple'),
                OuiVendor(prefix='BC4CC4', vendor='Apple'),
                OuiVendor(prefix='BC6778', vendor='Apple'),
                OuiVendor(prefix='C0847A', vendor='Apple'),
                OuiVendor(prefix='C0CECD', vendor='Apple'),
                OuiVendor(prefix='C0D012', vendor='Apple'),
                OuiVendor(prefix='C42C03', vendor='Apple'),
                OuiVendor(prefix='C81EE7', vendor='Apple'),
                OuiVendor(prefix='C86F1D', vendor='Apple'),
                OuiVendor(prefix='C8BCC8', vendor='Apple'),
                OuiVendor(prefix='CC29F5', vendor='Apple'),
                OuiVendor(prefix='D023DB', vendor='Apple'),
                OuiVendor(prefix='D03311', vendor='Apple'),
                OuiVendor(prefix='D065CA', vendor='Apple'),
                OuiVendor(prefix='D4619D', vendor='Apple'),
                OuiVendor(prefix='D49A20', vendor='Apple'),
                OuiVendor(prefix='D81D72', vendor='Apple'),
                OuiVendor(prefix='D83062', vendor='Apple'),
                OuiVendor(prefix='D89695', vendor='Apple'),
                OuiVendor(prefix='D8A25E', vendor='Apple'),
                OuiVendor(prefix='DC0B34', vendor='Apple'),
                OuiVendor(prefix='DC9B9C', vendor='Apple'),
                OuiVendor(prefix='E02A82', vendor='Apple'),
                OuiVendor(prefix='E05FB9', vendor='Apple'),
                OuiVendor(prefix='E0ACCB', vendor='Apple'),
                OuiVendor(prefix='E0B9BA', vendor='Apple'),
                OuiVendor(prefix='E0C767', vendor='Apple'),
                OuiVendor(prefix='E425E7', vendor='Apple'),
                OuiVendor(prefix='E80688', vendor='Apple'),
                OuiVendor(prefix='EC3586', vendor='Apple'),
                OuiVendor(prefix='F01898', vendor='Apple'),
                OuiVendor(prefix='F02475', vendor='Apple'),
                OuiVendor(prefix='F0761C', vendor='Apple'),
                OuiVendor(prefix='F099BF', vendor='Apple'),
                OuiVendor(prefix='F0B479', vendor='Apple'),
                OuiVendor(prefix='F0CBA1', vendor='Apple'),
                OuiVendor(prefix='F41563', vendor='Apple'),
                OuiVendor(prefix='F437B7', vendor='Apple'),
                OuiVendor(prefix='F45C89', vendor='Apple'),
                OuiVendor(prefix='F81EDF', vendor='Apple'),
                OuiVendor(prefix='F82793', vendor='Apple'),
                OuiVendor(prefix='F86214', vendor='Apple'),
                OuiVendor(prefix='FC253F', vendor='Apple'),
                OuiVendor(prefix='FCFC48', vendor='Apple'),
                OuiVendor(prefix='0050F2', vendor='Microsoft'),
                OuiVendor(prefix='00155D', vendor='Microsoft'),
                OuiVendor(prefix='0017FA', vendor='Microsoft'),
                OuiVendor(prefix='001D09', vendor='Microsoft'),
                OuiVendor(prefix='002248', vendor='Microsoft'),
                OuiVendor(prefix='002316', vendor='Microsoft'),
                OuiVendor(prefix='0025AE', vendor='Microsoft'),
                OuiVendor(prefix='00E04C', vendor='Realtek'),
                OuiVendor(prefix='000CE7', vendor='Motorola'),
                OuiVendor(prefix='8217AF', vendor='Xiaomi'),
                OuiVendor(prefix='CA7D57', vendor='Samsung'),
                OuiVendor(prefix='928D37', vendor='Huawei'),
                OuiVendor(prefix='FAF566', vendor='Oppo'),
                OuiVendor(prefix='669A95', vendor='Vivo'),
                OuiVendor(prefix='AAF94F', vendor='Realme'),
                OuiVendor(prefix='1626D7', vendor='Xiaomi'),
                OuiVendor(prefix='1EB5B9', vendor='Samsung'),
                OuiVendor(prefix='3C5AB4', vendor='Google'),
                OuiVendor(prefix='AC3743', vendor='Huawei'),
                OuiVendor(prefix='FCDC4F', vendor='Samsung'),
                OuiVendor(prefix='380E4D', vendor='Xiaomi'),
                OuiVendor(prefix='480EEC', vendor='Samsung'),
                OuiVendor(prefix='549A0F', vendor='Oppo'),
                OuiVendor(prefix='703ACE', vendor='Vivo'),
                OuiVendor(prefix='001A11', vendor='Samsung'),
                OuiVendor(prefix='001D0D', vendor='Sony'),
                OuiVendor(prefix='001EDC', vendor='Samsung'),
                OuiVendor(prefix='002119', vendor='Samsung'),
                OuiVendor(prefix='002339', vendor='Samsung'),
                OuiVendor(prefix='002454', vendor='Samsung'),
                OuiVendor(prefix='002666', vendor='Samsung'),
                OuiVendor(prefix='00E061', vendor='Samsung'),
                OuiVendor(prefix='0808C2', vendor='Samsung'),
                OuiVendor(prefix='0C1420', vendor='Samsung'),
                OuiVendor(prefix='103025', vendor='Samsung'),
                OuiVendor(prefix='14F65A', vendor='Xiaomi'),
                OuiVendor(prefix='182195', vendor='Samsung'),
                OuiVendor(prefix='1C62B8', vendor='Samsung'),
                OuiVendor(prefix='240AC4', vendor='Vivo'),
                OuiVendor(prefix='286CAB', vendor='Xiaomi'),
                OuiVendor(prefix='2C5491', vendor='Xiaomi'),
                OuiVendor(prefix='380B40', vendor='Samsung'),
                OuiVendor(prefix='44650D', vendor='Samsung'),
                OuiVendor(prefix='48137E', vendor='Samsung'),
                OuiVendor(prefix='4C3B74', vendor='Huawei'),
                OuiVendor(prefix='50642B', vendor='Xiaomi'),
                OuiVendor(prefix='549B12', vendor='Samsung'),
                OuiVendor(prefix='582D34', vendor='Oppo'),
                OuiVendor(prefix='5C497D', vendor='Samsung'),
                OuiVendor(prefix='606BBD', vendor='Samsung'),
                OuiVendor(prefix='683E26', vendor='Oppo'),
                OuiVendor(prefix='6C709F', vendor='Xiaomi'),
                OuiVendor(prefix='78521A', vendor='Samsung'),
                OuiVendor(prefix='804A14', vendor='Oppo'),
                OuiVendor(prefix='881196', vendor='Huawei'),
                OuiVendor(prefix='904C81', vendor='Huawei'),
                OuiVendor(prefix='9C8CD8', vendor='Huawei'),
                OuiVendor(prefix='A0EDCD', vendor='Vivo'),
                OuiVendor(prefix='AC4223', vendor='Xiaomi'),
                OuiVendor(prefix='B06EBF', vendor='Oppo'),
                OuiVendor(prefix='B83765', vendor='Xiaomi'),
                OuiVendor(prefix='BC7FA8', vendor='Huawei'),
                OuiVendor(prefix='C0210D', vendor='Samsung'),
                OuiVendor(prefix='CC07AB', vendor='Xiaomi'),
                OuiVendor(prefix='D8490F', vendor='Huawei'),
                OuiVendor(prefix='E0DCA2', vendor='Vivo'),
                OuiVendor(prefix='E89C25', vendor='Asus'),
                OuiVendor(prefix='EC233D', vendor='Xiaomi'),
                OuiVendor(prefix='F077C8', vendor='Xiaomi'),
                OuiVendor(prefix='F83E95', vendor='Vivo'),
                OuiVendor(prefix='FC64BA', vendor='Xiaomi'),
                OuiVendor(prefix='043604', vendor='Huawei'),
                OuiVendor(prefix='0C771A', vendor='Oppo'),
                OuiVendor(prefix='185680', vendor='Oppo'),
                OuiVendor(prefix='2418C6', vendor='Vivo'),
                OuiVendor(prefix='286D97', vendor='Oppo'),
                OuiVendor(prefix='3431C4', vendor='Huawei'),
                OuiVendor(prefix='486DFB', vendor='Xiaomi'),
                OuiVendor(prefix='549A08', vendor='Oppo'),
                OuiVendor(prefix='644BF0', vendor='Xiaomi'),
                OuiVendor(prefix='683F7D', vendor='Oppo'),
                OuiVendor(prefix='6C5C3D', vendor='Huawei'),
                OuiVendor(prefix='788C77', vendor='Xiaomi'),
                OuiVendor(prefix='808917', vendor='Oppo'),
                OuiVendor(prefix='885A92', vendor='Huawei'),
                OuiVendor(prefix='98523D', vendor='Oppo'),
                OuiVendor(prefix='A48D3B', vendor='Vivo'),
                OuiVendor(prefix='B07C25', vendor='Xiaomi'),
                OuiVendor(prefix='B43052', vendor='Huawei'),
                OuiVendor(prefix='C0EEFB', vendor='Oppo'),
                OuiVendor(prefix='CC81DA', vendor='Vivo'),
                OuiVendor(prefix='D494E8', vendor='Huawei'),
                OuiVendor(prefix='E47E9A', vendor='Xiaomi'),
                OuiVendor(prefix='F4C714', vendor='Oppo'),
                OuiVendor(prefix='FC167D', vendor='Vivo'),
                OuiVendor(prefix='F49F54', vendor='Xiaomi'),
                OuiVendor(prefix='ACBCD7', vendor='Samsung'),
                OuiVendor(prefix='2C6939', vendor='Xiaomi'),
                OuiVendor(prefix='485929', vendor='Xiaomi'),
                OuiVendor(prefix='64CC2E', vendor='Xiaomi'),
                OuiVendor(prefix='A41115', vendor='Xiaomi'),
            ])
            self.stdout.write(self.style.SUCCESS('Seeded OuiVendor records.'))
            seeded = True
        else:
            self.stdout.write(self.style.NOTICE('OuiVendor records already exist, skipping.'))

        if not PortService.objects.exists():
            PortService.objects.bulk_create([
                PortService(port=21, service='FTP'),
                PortService(port=22, service='SSH'),
                PortService(port=23, service='Telnet'),
                PortService(port=25, service='SMTP'),
                PortService(port=53, service='DNS'),
                PortService(port=80, service='HTTP'),
                PortService(port=110, service='POP3'),
                PortService(port=139, service='NetBIOS'),
                PortService(port=143, service='IMAP'),
                PortService(port=443, service='HTTPS'),
                PortService(port=445, service='SMB'),
                PortService(port=993, service='IMAPS'),
                PortService(port=995, service='POP3S'),
                PortService(port=3389, service='RDP'),
                PortService(port=5353, service='mDNS'),
                PortService(port=5900, service='VNC'),
                PortService(port=631, service='IPP'),
                PortService(port=5000, service='UPnP'),
                PortService(port=7000, service='AirPlay'),
                PortService(port=548, service='AFP'),
                PortService(port=3306, service='MySQL'),
                PortService(port=5432, service='PostgreSQL'),
                PortService(port=27017, service='MongoDB'),
                PortService(port=6379, service='Redis'),
                PortService(port=11211, service='Memcached'),
                PortService(port=1433, service='MSSQL'),
                PortService(port=1521, service='Oracle'),
                PortService(port=2375, service='Docker'),
                PortService(port=3000, service='Node/HTTP'),
                PortService(port=9200, service='Elasticsearch'),
                PortService(port=5601, service='Kibana'),
            ])
            self.stdout.write(self.style.SUCCESS('Seeded PortService records.'))
            seeded = True
        else:
            self.stdout.write(self.style.NOTICE('PortService records already exist, skipping.'))

        cache.delete('scanner_oui_vendors')
        cache.delete('scanner_port_services')

        if not seeded:
            self.stdout.write(self.style.SUCCESS('Database already seeded. Nothing to do.'))
